-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 22:55:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema review_phim
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema review_phim
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `review_phim` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_vietnamese_ci ;
USE `review_phim` ;

-- -----------------------------------------------------
-- Table `review_phim`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `review_phim`.`movies` (
  `movie_id` INT NOT NULL AUTO_INCREMENT,
  `movie_name` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `release_date` DATE NULL DEFAULT NULL,
  `genre` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `director` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `average_grade` DECIMAL(3,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`movie_id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;
-- Add a new column for storing image URLs in the `movies` table
ALTER TABLE `review_phim`.`movies`
ADD COLUMN `image_url` VARCHAR(255) NOT NULL;

-- -----------------------------------------------------
-- Table `review_phim`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `review_phim`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;

-- -----------------------------------------------------
-- Table `review_phim`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `review_phim`.`feedback` (
  `feedback_id` INT NOT NULL AUTO_INCREMENT,
  `grade` INT NOT NULL DEFAULT '0',
  `comment` TEXT NULL DEFAULT NULL,
  `movie_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`feedback_id`),
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `feedback_movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `review_phim`.`movies` (`movie_id`),
  CONSTRAINT `feedback_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `review_phim`.`users` (`user_id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;

-- -----------------------------------------------------
-- Table `review_phim`.`feedback_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `review_phim`.`feedback_answer` (
  `answer_id` INT NOT NULL AUTO_INCREMENT,
  `answer` TEXT NULL DEFAULT NULL,
  `feedback_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`answer_id`),
  INDEX `feedback_id_idx` (`feedback_id` ASC) VISIBLE,
  CONSTRAINT `feedback_answer_feedback_id`
    FOREIGN KEY (`feedback_id`)
    REFERENCES `review_phim`.`feedback` (`feedback_id`),
  CONSTRAINT `feedback_answer_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `review_phim`.`users` (`user_id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;

-- Thêm cột `created_at` và `updated_at` vào bảng `feedback`
ALTER TABLE `review_phim`.`feedback`
ADD COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Thêm cột `created_at` và `updated_at` vào bảng `feedback_answer`
ALTER TABLE `review_phim`.`feedback_answer`
ADD COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- -----------------------------------------------------
-- Table `review_phim`.`urls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `review_phim`.`urls` (
  `url_id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`url_id`),
  CONSTRAINT `url_movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `review_phim`.`movies` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
